name: Code Analysis

on:
  workflow_dispatch:
  pull_request:

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check white-space
        run: yarn pretty

      - name: Build project
        run: yarn build

      - name: Lint
        run: yarn lint
